apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    k8s-app: api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    k8s-app: api