apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: fabmedweb 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fabmedweb 
    spec:
      containers:
        - name: fabmedweb 
          image: azninja.azurecr.io/fabmedweb 
          ports:
          - containerPort: 3000